Feature/deceleration
OUXT-Polaris/hermite_path_planner pull request #68
Opened 2023-03-15 12:22 UTC by kentohirogaki

velocity planning のテストを作成

2023-08-09 06:48 UTC, hakuturu583 requested changes

2023-08-09 06:48 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  // ASSERT_EQ("hoge", buf.str());
```suggestion
```

2023-08-14 05:19 UTC, hakuturu583 commented
This PR also support maximum deceleration.

2023-08-15 03:46 UTC, hakuturu583 requested changes

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  converted_constraints = velocity_planning::planVelocity(
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  std::vector<hermite_path_msgs::msg::ReferenceVelocity> converted_constraints;
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-08-15 03:46 UTC, hakuturu583 commented on velocity_planner/test/src/test_velocity_planning.cpp
> +  converted_constraints = velocity_planning::planVelocity(
`converted`はどういう操作をした変数かわかりません。
この関数の結果はPure Pursuit Plannerにおいて参照速度として使用されるため`reference_velocity`などが適切かと思います。
変数名に悩んだときはGoolgleで検索をするなりGithub Copilotに聞くことを推奨します。

2023-10-17 12:35 UTC, Tossy0423 requested changes
片岡さんが指摘されたところを修正・確認しました。
ローカル環境でのビルドをパスしてことも確認済です。

2023-10-17 13:32 UTC, hakuturu583 approved these changes

2023-10-17 13:34 UTC, merged